drop table if exists ss_task;
drop table if exists ss_user;
drop table if exists human;
drop table if exists employee;

create table ss_task (
	id bigint generated by default as identity,
	title varchar(128) not null,
	description varchar(255),
	user_id bigint not null,
    primary key (id)
);

create table ss_user (
	id bigint generated by default as identity,
	login_name varchar(64) not null unique,
	name varchar(64) not null,
	register_date timestamp not null,
	primary key (id)
);

create table human (
	id bigint generated by default as identity,
	name varchar(64) not null unique,
	english_name varchar(64) ,
	birthday date ,
	sex tinyint,
	phone varchar(11),
	email varchar (30),
	portrait varchar(30),
	primary key (id)
);

create table employee (
	id bigint generated by default as identity,
	position varchar(20),
	desc varchar(1000),
	company_id bigint,
	primary key (id)
);