-- noinspection SqlNoDataSourceInspectionForFile
drop table if exists ss_task;
drop table if exists ss_user;
drop table if exists human;
drop table if exists employee;

/*drop table if exists ss_collected_data;*/
create table ss_task (
	id bigint generated by default as identity,
	title varchar(128) not null,
	description varchar(255),
	user_id bigint not null,
  primary key (id)
);

create table ss_user (
	id bigint generated by default as identity,
	city varchar(64) DEFAULT null,
	sex tinyint(3),
	province varchar(64) DEFAULT null,
	`nick_name` varchar(64) DEFAULT null,
	remark_name varchar(64) DEFAULT null,
	create_date timestamp not null,
	uin INTEGER(11),
	head_img_url VARCHAR(100),
	primary key (id)
);

create table human (
	id bigint generated by default as identity,
	name varchar(64) not null unique,
	english_name varchar(64) ,
	birthday date ,
	sex tinyint,
	phone varchar(11),
	email varchar (30),
	portrait varchar(30),
	primary key (id)
);

create table employee (
	id bigint generated by default as identity,
	position varchar(20),
	desc varchar(1000),
	company_id bigint,
	primary key (id)
);
/*
create table if not exists ss_collected_data(
  id bigint generated by default as identity,
  type VARCHAR(20),
  data text,
  PRIMARY KEY (id)
);
*/